<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Tweet Away</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            background-color: #dfcaae;
            font-size: 18px;
        }
        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
        .btn{
            font-size: 25px;
            width:300px;
            padding:5px;
            
        }
    </style>
</head>
<body>
<img src="tweetaway.png" height="220" width="260"/>
<h1>Tweet Away</h1>
<div>A web social media application to waste away time!</div>

<div class="container mt-5">
        <button id="redirect-btn" class="btn btn-primary rounded ">Click To See Posts!</button>
</div>

<?php if (isset($name)) : ?>
    <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
<?php endif; ?>

</body>
</html>

<script type="text/javascript">
    document.getElementById("redirect-btn").onclick = function () {
        location.href = "/chat";
    };
</script>